If kafka truststore and keystore locations
spring-cloud/spring-cloud-stream pull request #2775
Opened 2023-07-14 13:09 UTC by gynoro

If kafka truststore and keystore locations are not local files, then they are converted to org.springframework.core.io.Resource resources, then copied to local file system. This means that, paths can be defined as http resources too. It is useful if you have a config server where your certificates reside.

2023-07-14 13:09 UTC, pivotal-cla commented
@gynoro Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=2775)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=2775) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-07-14 13:12 UTC, pivotal-cla commented
@gynoro Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream&pullRequestId=2775)!

2023-07-26 21:39 UTC, sobychacko requested changes

2023-07-26 21:39 UTC, sobychacko commented on binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaBinderConfigurationProperties.java
> +		} catch (Exception e) {
This needs to be on a new line. Can you run a full build and see if there are any checkstyle failures?

2023-07-26 21:39 UTC, sobychacko commented on docs/src/main/asciidoc/kafka/kafka_overview.adoc
> +When the truststore or keystore certificate location is given as a non-local file system resources, the binder copies the resource from the path (which is convertible to org.springframework.core.io.R
Could you add the various formats that it supports now? (`CLASSPATH`, `HTTP` etc. as examples)

2023-07-26 21:41 UTC, sobychacko commented
@gynoro Apologies for not reviewing the PR earlier. I added some minor comments. Could you take a look?
Did you test your changes against a proper application to see if it works seamlessly with `HTTP`? Also, please add your name as an author on the classes you modified and update copyright years if need be. Thank you.

2023-08-15 19:44 UTC, sobychacko commented
@gynoro Did you get a chance to go through the PR review comments? Please let us know so that we can move further along.

2023-08-24 08:43 UTC, gynoro commented
Hi @sobychacko, sorry for the delay. I fixed the heckstyle errors and extended the documentation. 
I only tested the http functionality against a mock server in `KafkaBinderConfigurationPropertiesTest`.

2023-09-05 17:18 UTC, sobychacko commented
@gynoro Sorry for the delay. Thanks for addressing the PR comments. It is now merged upstream via https://github.com/spring-cloud/spring-cloud-stream/commit/0949d4e14501da6fdbb9347e691b8cce0b2e49b9 and back-ported to `4.0.x`.

2023-09-05 17:18 UTC, closed without merging

2023-09-07 11:12 UTC, gynoro commented
@sobychacko What do you mean by "back-ported to 4.0.x"? What version?
In which version will be released this feature?

2023-09-07 15:57 UTC, sobychacko commented
`4.0.x` is the current GA line. The next release on this line is `4.0.5`. The current main branch is `4.1.x`. The first GA for this is planned for November. See the Spring Release [calendar](https://calendar.spring.io/) for more details.