Add @EnableTestBinder annotation
spring-cloud/spring-cloud-stream pull request #2947
Opened 2024-05-09 00:48 UTC by kutmk

- Added the `@EnableTestBinder` annotation to import `TestChannelBinderConfiguration` for enabling TestBinder. This was decided in issue #2931.
- Replaced `@Import(TestChannelBinderConfiguration.class)` with `@EnableTestBinder` in the tests.

2024-05-09 16:41 UTC, sobychacko requested changes

2024-05-09 16:41 UTC, sobychacko commented on core/spring-cloud-stream-test-binder/src/main/java/org/springframework/cloud/stream/binder/test/EnableTestBinder.java
> +
Could you add some class level javadoc to this?

2024-05-09 16:41 UTC, sobychacko commented on core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/binder/tck/ContentTypeTckTests.java
Need copyright updates, author tag.

2024-05-09 16:41 UTC, sobychacko commented on core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/binding/BindingServiceTests.java
Need copyright updates, author tag.

2024-05-09 16:41 UTC, sobychacko commented on core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/BindingHandlerAdviseTests.java
>  import static org.assertj.core.api.Assertions.assertThat;
Need copyright updates, author tag.

2024-05-09 16:41 UTC, sobychacko commented on core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/RetryTemplateTests.java
Need copyright updates, author tag.

2024-05-09 16:41 UTC, sobychacko commented
@kutmk Could you also add some documentation in the reference docs for this?

2024-05-10 20:07 UTC, kutmk commented
@sobychacko 
I have updated the copyright and author tags, added Javadoc, and also tried rewriting the reference docs.

2024-05-13 15:29 UTC, merged

2025-10-30 12:18 UTC, jonenst commented
Hi, could you share and maybe document a method to restore the old behavior ?

Specifically this diff in the docs,
```patch
- To enable Spring Integration test binder, all you need is to add it as a dependency.
+ To enable Spring Integration test binder, you need to add it as a dependency and annotate your class with `@EnableTestBinder`.
```

in my case I have dozens and dozens of classes, not just one. I never use mixed tests so the old behavior of always using testbinder as soon as it is in the classpath was exactly what I want. Is there an official way to avoid @EnableTestBinder in all my files ?

Thanks in advance


PS: In my case I have an even weirder behavior but I haven't investigated enough, When I run one @SpringBootTest and then another @SpringBootTest with import TestChannelBinderConfiguration.class, then the second test doesn't receive messages in the testbinder. Is there some static state that is carried over even though they are 2 different spring contexts ?? Is it possible or am I misdiagnosing this ?? (using spring cloud stream 4.2.2) (in my case the classpath contains both the rabbitmq binder and testbinder). This means that if I forget just one file, depending on the test order (hard to reproduce), other tests that do have the testbinder configured start to fail.